name: Validate Schema

on:
  pull_request:
    paths:
      - 'schema/**'
      - 'data/**'
      - 'tools/validator.py'
  push:
    branches: [main]
    paths:
      - 'schema/**'
      - 'data/**'
      - 'tools/validator.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Validate schema and data
        run: python tools/validator.py
